AWSTemplateFormatVersion: 2010-09-09
Description: A Sample Template of a Custom Conformance Pack
Parameters:
    ConformancePackDeliveryBucket:
        Type: String
        Description: AWS Config stores intermediate files while processing conformance pack template. Please enter thename of the bucket that has been configured already for conformance pack to deliver to deliver findings.
Resources:
  ConformancePack:
      Type: 'AWS::Config::ConformancePack'
      Properties: 
          ConformancePackName: custom-conformance-pack
          DeliveryS3Bucket: !Ref ConformancePackDeliveryBucket
          TemplateBody: |-
            Resources:
              CloudTrailCloudWatchLogsEnabled:
                Properties:
                  ConfigRuleName: cloud-trail-cloud-watch-logs-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED
                Type: AWS::Config::ConfigRule
              CloudTrailEnabled:
                Properties:
                  ConfigRuleName: cloudtrail-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: CLOUD_TRAIL_ENABLED
                Type: AWS::Config::ConfigRule
              CloudTrailEncryptionEnabled:
                Properties:
                  ConfigRuleName: cloud-trail-encryption-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: CLOUD_TRAIL_ENCRYPTION_ENABLED
                Type: AWS::Config::ConfigRule
              CloudTrailLogFileValidationEnabled:
                Properties:
                  ConfigRuleName: cloud-trail-log-file-validation-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: CLOUD_TRAIL_LOG_FILE_VALIDATION_ENABLED
                Type: AWS::Config::ConfigRule
              CloudtrailS3DataeventsEnabled:
                Properties:
                  ConfigRuleName: cloudtrail-s3-dataevents-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: CLOUDTRAIL_S3_DATAEVENTS_ENABLED
                Type: AWS::Config::ConfigRule
              CloudtrailSecurityTrailEnabled:
                Properties:
                  ConfigRuleName: cloudtrail-security-trail-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: CLOUDTRAIL_SECURITY_TRAIL_ENABLED
                Type: AWS::Config::ConfigRule
              MultiRegionCloudTrailEnabled:
                Properties:
                  ConfigRuleName: multi-region-cloudtrail-enabled
                  Source:
                    Owner: AWS
                    SourceIdentifier: MULTI_REGION_CLOUD_TRAIL_ENABLED
                Type: AWS::Config::ConfigRule
